# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
type:             'blog'
title:            'James Kyle'
tagline:          'Dat tagline tho'
description:      'Some developer guy from Boston'
url:              'http://thejameskyle.com'

author:
  name:           'James Kyle'
  url:            'https://github.com/thejameskyle'
  twitter:        '@thejameskyle'

keywords:
  - 'Programming'
  - 'Front End'
  - 'Web Development'
  - 'Open Source'
  - 'HTML'
  - 'CSS'
  - 'Javascript'
  - 'thejameskyle'
  - 'tjk'

image:
  url:            'http://thejameskyle.com/public/og-image.png'
  type:           'image/png'
  width:          '288'
  height:         '288'

paginate:         1

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/thejameskyle/thejameskyle.github.io
